python ./majority_voting_fair_english.py "1" 1 8
python ./majority_voting_fair_english.py "1" 2 4
python ./majority_voting_fair_english.py "1" 3 3
#python ./majority_voting_fair_english.py "2" 1 8
#python ./majority_voting_fair_english.py "2" 2 4
#python ./majority_voting_fair_english.py "2" 3 3
#python ./majority_voting_fair_english.py "3" 1 8
#python ./majority_voting_fair_english.py "3" 2 4
#python ./majority_voting_fair_english.py "3" 3 3